### PR TITLE
Fix "Don't know how to find @loader_path/libvl.dylib, skipping" and add toolchain.

### PR DESCRIPTION
**Pull request by 183amir**

### CODE REVIEW

**Comment by 183amir** [comment]
We really need to fix this error: `Don't know how to find @loader_path/libvl.dylib, skipping`. It is making the `vlfeat` package unusable: https://github.com/conda-forge/bob.ip.base-feedstock/pull/2#issuecomment-220799955

**Comment by patricksnape** [comment]
How does this fix this problem? I had already fixed it manually and now it is failing again.

**Comment by 183amir** [comment]
I was hoping adding the toolchain would somehow fix it. And the way you did it, we have to manually fix every code that links against vlfeat. We need another solution.

**Comment by patricksnape** [comment]
You'll have to patch the makefile then.

**Comment by 183amir** [comment]
Which part of the makefile? I have no idea how things work in mac.

**Comment by patricksnape** [comment]
@183amir Re-add the `install_name_tool` logic at the bottom as follows:

```
# For some reason the instal_name_tool fails, so I do it manually here
if [ "$(uname -s)" == "Darwin" ]; then
  install_name_tool -id @rpath/libvl.dylib $PREFIX/lib/libvl.dylib
  install_name_tool -change @loader_path/libvl.dylib @rpath/../lib/libvl.dylib $PREFIX/bin/sift
  install_name_tool -change @loader_path/libvl.dylib @rpath/../lib/libvl.dylib $PREFIX/bin/mser
  install_name_tool -change @loader_path/libvl.dylib @rpath/../lib/libvl.dylib $PREFIX/bin/aib
fi
```

Notice I now fix the `id` as well. This fixes the `bob.ip` error on my Mac without any changes to the bob recipe.

**Comment by 183amir** [comment]
@patricksnape why do I still have to change the binary files?

**Comment by patricksnape** [comment]
Because they are separate issues. The issue is that the library_name isn't set up correctly in the Vlfeat Makefile and so it looks for libvl in the wrong place. This is simpler than patching the Makefile + I'm not actually that experienced with sorting these types of Makefile errors out.

**Comment by 183amir** [comment]
@patricksnape Good to be merged now?

**Comment by patricksnape** [comment]
Yup LGTM

**Pull request merged**
